job:
  name: ansible-demo
  ttlSecondsAfterFinished: 600
  restartPolicy: Never

namespace:
  name: ansible-runner
  create: true

ansible:
  repository:
   
    url: "https://github.com/redhat-gpst/cohestity-ve-rhdp-lab"
    branch: "main"
    path: "playbooks"

  # Main playbook to execute
  playbook: "site.yml"

  # Python packages to install
  requirements:
    - ansible-core
    - ansible-runner
    - kubernetes
    - openshift
    - PyYAML
    - requests